theme: jekyll-theme-hacker
title: Chris Razo's Digital Portfolio
description: A professional portfolio showcasing my projects, labs, and skills.
baseurl: "/portfolio-v2"
url: "https://c-razo.github.io"
