theme: jekyll-theme-hacker
title: Chris Razo's Cybersecurity Portfolio
description: A professional portfolio showcasing my cybersecurity projects, labs, and skills.
baseurl: "/portfolio-v2"
url: "https://c-razo.github.io"
